-- SQL to update the existing 'customer' table schema.
-- This is a manual migration step and should be run directly on your database.

-- IMPORTANT: Backup your database before running schema modifications!

-- Step 1: Alter 'password' column to VARCHAR(255) for hashed passwords
ALTER TABLE `customer`
MODIFY COLUMN `password` VARCHAR(255) NOT NULL;

-- Step 2: Add 'role' column with a default value
ALTER TABLE `customer`
ADD COLUMN `role` VARCHAR(50) NOT NULL DEFAULT 'user';

-- Optional: If you need to update existing users to 'admin' role
-- UPDATE `customer` SET `role` = 'admin' WHERE `username` = 'your_admin_username';

-- Example of a full customer table definition after changes (for reference, not to be run as an UPDATE)
-- CREATE TABLE `customer` (
--   `customer_id` int(11) NOT NULL AUTO_INCREMENT,
--   `username` varchar(255) NOT NULL UNIQUE,
--   `email` varchar(255) NOT NULL UNIQUE,
--   `password` varchar(255) NOT NULL, -- Changed to 255
--   `phone` varchar(20) DEFAULT NULL,
--   `address` varchar(255) DEFAULT NULL,
--   `dob` date DEFAULT NULL,
--   `role` varchar(50) NOT NULL DEFAULT 'user', -- New column
--   PRIMARY KEY (`customer_id`)
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- If you have a 'feedback' table, ensure it has `customer_id` as foreign key
-- CREATE TABLE `feedback` (
--   `feedback_id` int(11) NOT NULL AUTO_INCREMENT,
--   `customer_id` int(11) NOT NULL,
--   `subject` varchar(255) NOT NULL,
--   `message` text NOT NULL,
--   `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
--   PRIMARY KEY (`feedback_id`),
--   KEY `customer_id` (`customer_id`),
--   CONSTRAINT `feedback_ibfk_1` FOREIGN KEY (`customer_id`) REFERENCES `customer` (`customer_id`) ON DELETE CASCADE
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- If you have a 'booking' table, ensure it has `customer_id` and `transaction_id`
-- ALTER TABLE `booking`
-- ADD COLUMN `transaction_id` VARCHAR(255) NULL AFTER `status`; -- Add this if not present

-- Example booking table structure
-- CREATE TABLE `booking` (
--   `booking_id` int(11) NOT NULL AUTO_INCREMENT,
--   `customer_id` int(11) NOT NULL,
--   `destination_id` int(11) NOT NULL,
--   `booking_date` date NOT NULL,
--   `travel_date` date NOT NULL,
--   `num_travelers` int(11) NOT NULL DEFAULT 1,
--   `total_price` decimal(10,2) NOT NULL,
--   `status` varchar(50) NOT NULL DEFAULT 'Pending', -- Can be Pending, Confirmed, Cancelled, Refunded, Refund Requested
--   `transaction_id` varchar(255) DEFAULT NULL, -- For payment gateway transaction IDs
--   PRIMARY KEY (`booking_id`),
--   KEY `customer_id` (`customer_id`),
--   KEY `destination_id` (`destination_id`),
--   CONSTRAINT `booking_ibfk_1` FOREIGN KEY (`customer_id`) REFERENCES `customer` (`customer_id`) ON DELETE CASCADE,
--   CONSTRAINT `booking_ibfk_2` FOREIGN KEY (`destination_id`) REFERENCES `destination` (`destination_id`) ON DELETE CASCADE
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Add a sample admin user if needed (replace 'admin_password_hash' with a real hash generated by PHP's password_hash())
-- INSERT INTO `customer` (`username`, `email`, `password`, `phone`, `address`, `dob`, `role`)
-- VALUES ('admin', 'admin@example.com', '$2y$10$YourGeneratedHashedPasswordHere.SomeSaltAndCharacters', NULL, NULL, NULL, 'admin');
-- Remember to generate a hash for 'admin' using password_hash('your_chosen_admin_password', PASSWORD_DEFAULT) in a separate script.